/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import SerialPort.Serial;
import gnu.io.NoSuchPortException;
import gnu.io.PortInUseException;
import gnu.io.UnsupportedCommOperationException;
import java.awt.Color;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JSpinner;

/**
 *
 * @author DiSCLAiMER
 */
public class gui extends javax.swing.JFrame {

    /**
     * Creates new form gui
     */
    public gui() {
        initComponents();
        this.getContentPane().setBackground(Color.BLACK);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinner3 = new javax.swing.JSpinner();
        factorSpinner = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        bar1Spinner = new javax.swing.JSpinner();
        bar2Spinner = new javax.swing.JSpinner();
        bar4Spinner = new javax.swing.JSpinner();
        bar3Spinner = new javax.swing.JSpinner();
        bar5Spinner = new javax.swing.JSpinner();
        bar6Spinner = new javax.swing.JSpinner();
        setConfigBtn = new javax.swing.JButton();
        readConfigBtn = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        factorSpinner.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(10.0f), Float.valueOf(10.0f), Float.valueOf(99.99f), Float.valueOf(0.01f)));
        factorSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                factorSpinnerStateChanged(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Vehicle Speed Sensor scaling factor");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel3.setFont(new java.awt.Font("Corbel", 1, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 0, 51));
        jLabel3.setText("    Bar 1");

        jLabel4.setFont(new java.awt.Font("Corbel", 1, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 0, 51));
        jLabel4.setText("    Bar 2");

        jLabel5.setFont(new java.awt.Font("Corbel", 1, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 0, 51));
        jLabel5.setText("    Bar 3");

        jLabel6.setFont(new java.awt.Font("Corbel", 1, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 0, 51));
        jLabel6.setText("    Bar 4");

        jLabel7.setFont(new java.awt.Font("Corbel", 1, 13)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 0, 51));
        jLabel7.setText("    Bar 5");

        jLabel8.setFont(new java.awt.Font("Corbel", 1, 13)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 0, 51));
        jLabel8.setText("    Bar 6");

        setConfigBtn.setText("Set Config");
        setConfigBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setConfigBtnActionPerformed(evt);
            }
        });

        readConfigBtn.setText("Read Config");
        readConfigBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                readConfigBtnActionPerformed(evt);
            }
        });

        jLabel9.setBackground(new java.awt.Color(0, 0, 0));

        jLabel2.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Engine Coolant Temperature gauge");

        jLabel10.setFont(new java.awt.Font("Corbel", 3, 22)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("cluster retrofit 1.0");

        jLabel11.setFont(new java.awt.Font("Corbel", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Created by Pablo Buenaposada");

        jLabel13.setFont(new java.awt.Font("Corbel", 0, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("                                              Degree Celsius scale (Cº)");

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(jLabel11)
                        .add(36, 36, 36)
                        .add(jButton1))
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                .add(layout.createSequentialGroup()
                                    .add(24, 24, 24)
                                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                        .add(jLabel2)
                                        .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 264, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .add(layout.createSequentialGroup()
                                            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                                                .add(jLabel3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .add(bar1Spinner, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))
                                            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                                .add(layout.createSequentialGroup()
                                                    .add(readConfigBtn)
                                                    .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 29, Short.MAX_VALUE)
                                                    .add(setConfigBtn))
                                                .add(layout.createSequentialGroup()
                                                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                                        .add(bar2Spinner, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                                                        .add(jLabel4, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                    .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                                        .add(bar3Spinner, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                                                        .add(jLabel5, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                    .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                                        .add(bar4Spinner, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                                                        .add(jLabel6, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                    .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                                        .add(bar5Spinner, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                                                        .add(jLabel7, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                                .add(bar6Spinner, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                                                .add(jLabel8, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .add(factorSpinner, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 69, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                                .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                                    .add(23, 23, 23)
                                    .add(jLabel12)
                                    .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                    .add(jLabel10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 185, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                            .add(layout.createSequentialGroup()
                                .add(60, 60, 60)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                    .add(jLabel9, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .add(jLabel13, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .add(0, 11, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(12, 12, 12)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jLabel10, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jLabel12, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(jLabel1)
                        .add(16, 16, 16)
                        .add(factorSpinner, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(18, 18, 18)
                        .add(jLabel2)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(jLabel9)
                        .add(0, 0, 0)
                        .add(jLabel13)
                        .add(10, 10, 10)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                    .add(jLabel3)
                                    .add(jLabel4))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(bar1Spinner, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(bar2Spinner, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                .add(bar5Spinner, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(layout.createSequentialGroup()
                                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                        .add(jLabel7)
                                        .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                            .add(jLabel6)
                                            .add(jLabel5)))
                                    .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                        .add(bar3Spinner, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .add(bar4Spinner, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                                .add(layout.createSequentialGroup()
                                    .add(jLabel8)
                                    .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                    .add(bar6Spinner, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                        .add(18, 18, Short.MAX_VALUE)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(readConfigBtn)
                            .add(setConfigBtn))
                        .add(18, 18, 18)
                        .add(jLabel11))
                    .add(layout.createSequentialGroup()
                        .add(0, 0, Short.MAX_VALUE)
                        .add(jButton1)))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void factorSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_factorSpinnerStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_factorSpinnerStateChanged

    private int celsius2ADC(int temp){
        ///return (int)((3.265034284*(Math.pow(10, -19))*Math.pow(temp,10) - 1.951343817*(Math.pow(10, -16))*Math.pow(temp,9) + 4.870935413*(Math.pow(10, -14))*Math.pow(temp,8) - 6.647521002*(Math.pow(10, -12))*Math.pow(temp,7) + 5.449673997*(Math.pow(10, -10))*Math.pow(temp,6) - 2.706842568*(Math.pow(10, -8))*Math.pow(temp,5) + 6.673031789*(Math.pow(10, -7))*Math.pow(temp,4) + 4.716273857*(Math.pow(10, -6))*Math.pow(temp,3) - 3.72064706*(Math.pow(10, -4))*Math.pow(temp,2) - 4.939427319*(Math.pow(10, -2))*temp + 3.485338965)*(1024/5));
        double adc = 6.635798591*Math.pow(10,-18)*Math.pow(temp,10) - 3.480638401*Math.pow(10,-15)*Math.pow(temp,9) + 6.704626343*Math.pow(10,-13)*Math.pow(temp,8) - 5.336340831*Math.pow(10,-11)*Math.pow(temp,7) + 1.138079742*Math.pow(10,-9)*Math.pow(temp,6) + 3.884963462*Math.pow(10,-10)*Math.pow(temp,5) - 7.333856047*Math.pow(10,-7)*Math.pow(temp,4) + 1.407153592*Math.pow(10,-3)*Math.pow(temp,3) - 8.970575209*Math.pow(10,-2)*Math.pow(temp,2) - 8.438835855*temp + 795.7698102;
        return (int) adc;
        
        //double celsuis = (0.1423*Math.pow(temp,6)) - (2.4938*Math.pow(temp,5))  + (17.837*Math.pow(temp,4)) - (68.698*Math.pow(temp,3)) + (154.69*Math.pow(temp,2)) - (232.75*temp) + 284.24;
        //return ((temp - 32)*5)/9;        
    }
    
    private int ADC2Celsius(int adc){
        double temp = -5.305551811*Math.pow(10,-30)*Math.pow(adc,10) + 2.118880391*Math.pow(10,-26)*Math.pow(adc,9) - 3.637655991*Math.pow(10,-23)*Math.pow(adc,8)+ 3.505260564*Math.pow(10,-20)*Math.pow(adc,7) + 1.05045638*Math.pow(10,-15)*Math.pow(adc,6) - 3.837648081*Math.pow(10,-12)*Math.pow(adc,5)+ 5.631122679*Math.pow(10,-9)*Math.pow(adc,4)- 4.44258481*Math.pow(10,-6)*Math.pow(adc,3) + 2.04885862*Math.pow(10,-3)*Math.pow(adc,2) - 6.314312776*Math.pow(10,-1)*adc + 140.1463525;
        return (int) temp;
    }
    
    private void setConfigBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setConfigBtnActionPerformed
        
        Serial serialPort = new Serial();
        try{
            serialPort.configPort("/dev/tty.usbserial","aa");
            Float factor = (Float)factorSpinner.getValue();
            factor = factor*100;
            System.out.println("VSSSET"+factor.intValue()+Character.toString('\n'));
            serialPort.write("VSSSET"+factor.intValue()+Character.toString('\n'));
            Thread.sleep(800);
            System.out.print(serialPort.read());        
            
        } catch (Exception ex) {
            Logger.getLogger(gui.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            serialPort.closePort();
        } catch (IOException ex) {
            Logger.getLogger(gui.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        int temp1 = Integer.parseInt(bar1Spinner.getValue().toString());
        int temp2 = Integer.parseInt(bar2Spinner.getValue().toString());
        int temp3 = Integer.parseInt(bar3Spinner.getValue().toString());
        int temp4 = Integer.parseInt(bar4Spinner.getValue().toString());
        int temp5 = Integer.parseInt(bar5Spinner.getValue().toString());
        int temp6 = Integer.parseInt(bar6Spinner.getValue().toString());        
        
        temp1 = celsius2ADC(temp1);
        temp2 = celsius2ADC(temp2);
        temp3 = celsius2ADC(temp3);
        temp4 = celsius2ADC(temp4);
        temp5 = celsius2ADC(temp5);
        temp6 = celsius2ADC(temp6); 
        
        /*temp1 = 203;
        temp2 = 156;
        temp3 = 122;
        temp4 = 84;
        temp5 = 53;
        temp6 = 19;*/
        
        String bar1 = String.format("%04d",temp1); 
        String bar2 = String.format("%04d",temp2); 
        String bar3 = String.format("%04d",temp3); 
        String bar4 = String.format("%04d",temp4); 
        String bar5 = String.format("%04d",temp5); 
        String bar6 = String.format("%04d",temp6); 
        
        System.out.println(bar1);
        
        
        Serial serialPort2 = new Serial();
        try{
            serialPort2.configPort("/dev/tty.usbserial","aa");
            serialPort2.write("ECTSET"+bar1+bar2+bar3+bar4+bar5+bar6+Character.toString('\n'));
            Thread.sleep(800);
            System.out.print(serialPort2.read());        
            
        } catch (Exception ex) {
            Logger.getLogger(gui.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            serialPort2.closePort();
        } catch (IOException ex) {
            Logger.getLogger(gui.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
    }//GEN-LAST:event_setConfigBtnActionPerformed

    private void readConfigBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readConfigBtnActionPerformed
        
        Serial serialPort = new Serial();
        try {
            serialPort.configPort("/dev/tty.usbserial","aa");
            serialPort.write("VSSREAD"+Character.toString('\n'));
            Thread.sleep(800);
            String received = serialPort.read();   
            System.out.println(received);
            int factorHigh = Integer.parseInt(received.substring(9,11));
            int factorLow = Integer.parseInt(received.substring(11,received.length()-2));            
            factorSpinner.setValue((float)((factorHigh*100)+factorLow)/100); 
            
        } catch (Exception ex) {            
            Logger.getLogger(gui.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            serialPort.closePort();
        } catch (IOException ex) {
            Logger.getLogger(gui.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        Serial serialPort2 = new Serial();
            
            
            try {
                serialPort2.configPort("/dev/tty.usbserial","aa");
                serialPort2.write("ECTREAD"+Character.toString('\n'));
                Thread.sleep(800);
                String received = serialPort.read(); 
                System.out.println(received);
                String[] split = received.substring(9).split("\\.");            
                bar1Spinner.setValue(ADC2Celsius(Integer.parseInt(split[0])));
                bar2Spinner.setValue(ADC2Celsius(Integer.parseInt(split[1])));
                bar3Spinner.setValue(ADC2Celsius(Integer.parseInt(split[2])));
                bar4Spinner.setValue(ADC2Celsius(Integer.parseInt(split[3])));
                bar5Spinner.setValue(ADC2Celsius(Integer.parseInt(split[4])));
                bar6Spinner.setValue(ADC2Celsius(Integer.parseInt(split[5].substring(0, split[5].length()-2))));                       
                
            } catch (Exception ex) {
                Logger.getLogger(gui.class.getName()).log(Level.SEVERE, null, ex);
            }
        try {
            serialPort2.closePort();
        } catch (IOException ex) {
            Logger.getLogger(gui.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
    }//GEN-LAST:event_readConfigBtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       Serial serialPort = new Serial();
        try {
            serialPort.configPort("/dev/tty.usbserial","aa");
            serialPort.write("ECTNOW"+Character.toString('\n'));
            Thread.sleep(800);
            String received = serialPort.read();   
            System.out.println(received);
            
            
        } catch (Exception ex) {            
            Logger.getLogger(gui.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            serialPort.closePort();
        } catch (IOException ex) {
            Logger.getLogger(gui.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gui().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner bar1Spinner;
    private javax.swing.JSpinner bar2Spinner;
    private javax.swing.JSpinner bar3Spinner;
    private javax.swing.JSpinner bar4Spinner;
    private javax.swing.JSpinner bar5Spinner;
    private javax.swing.JSpinner bar6Spinner;
    private javax.swing.JSpinner factorSpinner;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSpinner jSpinner3;
    private javax.swing.JButton readConfigBtn;
    private javax.swing.JButton setConfigBtn;
    // End of variables declaration//GEN-END:variables
}
